### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by tushar5526** [tushar5526/Autotype#17]
https://github.com/tushar5526/Autotype#run-it-as-follows-if-you-are-not-familiar-with-cli-apps

This is outdated. Update accordingly.

**Comment by Mr-Sunglasses** [comment]
I am creating sphinx docs for Autotype.

**Comment by RyanWalker277** [comment]
@tushar5526 I would like to know a bit more about the issue in order to properly update the documentation.Also , I tried to run the `simulate_keyboard.py` but it executed without typing anything.There weren't any errors but the script just didn't work.I followed the documentation for `simulate_keyboard.py` , has the method to use the script changed?

**Comment by tushar5526** [comment]
You might had to put the text to be typed inside that file and then run. 

Update the gif, showing cli and gui process

**Comment by Mr-Sunglasses** [comment]
Also try to find any online platform to upload demo gifs to reduce repo size.

**Comment by Bharadwajshivam28** [comment]
@Mr-Sunglasses PLease assign this to me sir

**Comment by Bharadwajshivam28** [comment]
@Mr-Sunglasses Assign this issue to me sir

**Comment by Bharadwajshivam28** [comment]
sorry sir @RyanWalker277

**Comment by Anubhavsoni001** [comment]
@tushar5526 Hello sir, I want to work on this issue please assign this to me.

**Comment by RyanWalker277** [comment]
Hey @Anubhavsoni001 ! @Bharadwajshivam28 is already working on this one , you can explore other issues in the meanwhile. #3 and  #4 can be a good start.
