### ISSUE TITLE
Add the black formatter GitHub Action 

### ISSUE THREAD

**Issue by Mr-Sunglasses** [tushar5526/Autotype#21]
# Add the black formatter GitHub Action 

## Overview
Currently, there is no Code Formatter used in Autotype, Our Goal is to add a Black code formattingr in Autotype.

## Description
Describe the solution you'd like -  Add a GitHub action that checks a PR for coding style using [black](https://pypi.org/project/black/). The GHA should be able to format the code and commit it to the PR if the PR is not following the coding style.

## Expected outcomes

A uniform coding style across Autotype, that Autoformat code on every PR.

## Skills

GitHub Actions, Python

## Possible mentors
[Kanishk Pachauri](https://github.com/Mr-Sunglasses), [Anjuman Hassan](https://github.com/AnjumanHasan)

## Expected project size

50 hours.

## Difficulty

Hard.

**Comment by AnjumanHasan** [comment]
[Use this Video for Reference](https://www.youtube.com/watch?v=TLB5MY9BBa4&t=2202s)

**Comment by Srijan-SS02** [comment]
# Add the black formatter GitHub Action

 ### My Background and Technical Skills
I have been into coding stuff since class 8th trying my hands on Python and its libraries like Pandas etc. Right now i'm handy with WebD, Python, C++ and in designing I have worked on Figma.  

 ### What problem are you trying to solve and Your Approach?
So I am trying to add the black formatter  through github action. Black formatter is python libraries which auto formats the code like indentation and other things. Which ultimately saves user time who will push there messy code.
I have also created a sample github action in one of my repo which uses super-Linter to check format of code.
linnk to it  : https://github.com/Srijan-SS02/ActionDemo  

 ### Your Timeline to solve the problem.
10th Sep 2022 : get  the project  assigned by Mentors and try to interact with mentors
11th Sep 2022 : trying to solve the issue and trying to get helped by the mentors
12th Sep 2022 : wrapping up the issue and fixing the minor bugs if any

@Mr-Sunglasses  @AnjumanHasan tagging maintainers for better reach

**Comment by AnjumanHasan** [comment]
Thanks @Srijan-SS02 for showing the Interest in the issue, You Proposal is Looking good, I'm assigning you the Issue, Best Wishes for your Contribution Journey, If you feel any problem or need any help just tag me or @Mr-Sunglasses .

**Comment by AnjumanHasan** [comment]
@Srijan-SS02 Take a look at [this example](https://github.com/The-Codesis/simple-static-website/pull/37/files) You'll know what's our Idea to use Black here in Autotype.

**Comment by Srijan-SS02** [comment]
@AnjumanHasan  @Mr-Sunglasses please review this PR and if there are any changes do let me know.

**Comment by Mr-Sunglasses** [comment]
Thanks, @Srijan-SS02 for solving this issue, and thanks @AnjumanHasan for assisting me and helping me for this issues.
