### ISSUE TITLE
Adding virtualenv setup steps to the Readme

### ISSUE THREAD

**Issue by RyanWalker277** [tushar5526/Autotype#44]
## Description

Many new contributors are facing issues wth `pipenv`. It would be better to provide them alternate setiup instructions with classic `virtualenv`. 

### Changes

- [ ] Add setup instructions to the readme with `virtualenv`

**Comment by huyta55** [comment]
Hi, I would like to work on this issue but wanted some clarification since I am a new contributor to this repo. Would solving this issue simple involve me writing out instructions on how to create a python virtual environment with virtualenv? or is there something specific to Autotype that is also involved?

**Comment by Nandani14** [comment]
@RyanWalker277 Please review the PR #50 for the following issue.
