### ISSUE TITLE
Reduce the project Size.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [tushar5526/Autotype#56]
Currenty due to all that demo media the size of the project is around `70 mb` we need to get in down.

**Comment by AkhilAndroid** [comment]
The GitHub repository's "open_file.gif" and "type_code.gif" graphics contain an issue. These  consume nearly 61MB of storage

I've got a plan. Instead of inserting them into the repository, we can keep these images via an image hosting site like Imgur. In this way, the load on the repository will be minimised because we only need to add the picture links.

I would be very glad to carry out this duty if you are okay with it. I'll compress those pictures and upload them to Imgur. I'll update the picture links in the required files once it is finished.

**Comment by AkhilAndroid** [comment]
@Mr-Sunglasses I have finished 

Please take a look at the pull request and review the changes and provide feedback.Let me know if any further adjustments or improvements are required.

**Comment by AkhilAndroid** [comment]
@Mr-Sunglasses you can close this issue
